# -*- coding: utf-8 -*-
"""data cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMvZswXefYqQNAl5DrE3ovg7uKx8Om2w
"""

import pandas as pd
import numpy as np

df=pd.read_csv("gurgaon_10k[1].csv")

df

df.drop(["PHOTO_URL","MEDIUM_PHOTO_URL"],axis=1,inplace=True)

df.head()

df.info()

df.isnull().sum()

df.columns

null_cols={"column_names":"no.of_nulls"}

for i in df.columns:
  if df[i].isnull().sum() > 3000:
    null_cols.update({i:int(df[i].isnull().sum())})
    df.drop(i,axis=1,inplace=True)

null_cols

df.columns

df['metadata']

df.drop(['xid','profile','PROP_ID','REGISTER_DATE','MIN_PRICE','BUILDING_ID','MIN_AREA_SQFT','AMENITIES','PD_URL','EXPIRY_DATE','GROUP_NAME','PROP_NAME','PROP_DETAILS_URL','CLASS_HEADING','CLASS_LABEL','PROPERTY_IMAGES','THUMBNAIL_IMAGES','CONTACT_NAME', 'CONTACT_COMPANY_NAME','DEALER_PHOTO_URL','BUILDING_NAME', 'CITY_ID','profile', 'xid','metadata'],axis=1,inplace=True)

df.columns

df.info()

df.isnull().sum()

df.SOCIETY_NAME.value_counts()



df['society']=df['SOCIETY_NAME'].str.lower()

df['society'].value_counts()

df.drop(['SOCIETY_NAME'],axis=1,inplace=True)

df.PRICE.value_counts()

import re

# Function to split number and unit
def separate_number_text(s):
    s = str(s).strip().lower().replace(",", "")

    # Handle range: "5.2 - 6.3 cr"
    range_match = re.match(r'^([\d\.]+)\s*-\s*([\d\.]+)\s*([a-zA-Z]*)$', s)
    if range_match:
        n1, n2 = float(range_match.group(1)), float(range_match.group(2))
        avg = (n1 + n2) / 2
        unit = range_match.group(3) if range_match.group(3) else None
        return str(avg), unit

    # Handle normal values: "3cr", "85,000", etc.
    match = re.match(r'^([\d\.]+)\s*([a-zA-Z]*)$', s)
    if match:
        number = match.group(1)
        unit = match.group(2) if match.group(2) else None
        return number, unit


df[['price_num', 'price_unit']] = df['PRICE'].apply(lambda x: pd.Series(separate_number_text(x)))

# Apply function
df[['price_num', 'price_unit']] = df['PRICE'].apply(
    lambda x: pd.Series(separate_number_text(x))
)

df[['PRICE','price_num', 'price_unit']]

df.price_num

df=df[df['PRICE'] != 'Price on Request']

df[df['PRICE'] !='Price on Request']



def convert_to_rupees(row):
    num = float(row['price_num'])
    unit = row['price_unit']

    if unit in ['cr']:
        return num * 10000000
    elif unit in ['l']:
        return num * 100000
    else:
        return num  # already in rupees

# Apply conversion
df['price_in_rupees'] = df.apply(convert_to_rupees, axis=1)

df['price_in_rupees']

df.info()

df.columns

df[['price_in_rupees','MAX_PRICE','MAX_AREA_SQFT','PRICE_SQFT','PRICE_PER_UNIT_AREA']]

df.drop(['price_in_rupees','PRICE_PER_UNIT_AREA'],axis=1,inplace=True)

'PRICE','price_num', 'price_unit'

df[['CITY', 'LOCALITY','society']]

df.PROPERTY_TYPE.value_counts()

df['sector'] = df['LOCALITY'].str.replace(r'\s*gurgaon$', '', case=False, regex=True)

df.drop([])

df.info()

from google.colab import files
df.to_csv('cleaned_data.csv', index=False)
files.download('cleaned_data.csv')

